version: '3'
services:
  laravel:
    build:
      context: ./docker
      dockerfile: laravel.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=rm-2zey75z6sqkkip75nko.mysql.rds.aliyuncs.com
      - DB_PORT=3306
      - DB_DATABASE=teaching
      - DB_USERNAME=nice
      - DB_PASSWORD=Memedama2
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TZ=Asia/Shanghai
    ports:
      - "9000:9000"
  redis:
    build:
      context: ./docker
      dockerfile: redis.dockerfile
    ports:
      - 63799:6379

  proxy:
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
    volumes:
      - ./:/var/www/:cached
    # 开发环境需取消端口调试开放
    ports:
      - 80:80
    links:
      - laravel
    working_dir: "/var/www"
    restart: "no"

